figure(); visualize_number(test_hop_net(w, zero, 1))
figure(); visualize_number(test_hop_net(w, one, 1))
figure(); visualize_number(test_hop_net(w, two, 1))
figure(); visualize_number(test_hop_net(w, three, 1))
figure(); visualize_number(test_hop_net(w, four, 1))
figure(); visualize_number(test_hop_net(w, five, 1))
figure(); visualize_number(test_hop_net(w, six, 1))
figure(); visualize_number(test_hop_net(w, seven, 1))
figure(); visualize_number(test_hop_net(w, eight, 1))
figure(); visualize_number(test_hop_net(w, nine, 1))

figure(); visualize_number(test_hop_net(w, noisy_digit(zero, 0.1), 1))
figure(); visualize_number(test_hop_net(w, noisy_digit(one, 0.1), 1))
figure(); visualize_number(test_hop_net(w, noisy_digit(two, 0.1), 1))
figure(); visualize_number(test_hop_net(w, noisy_digit(three, 0.1), 1))
figure(); visualize_number(test_hop_net(w, noisy_digit(four, 0.1), 1))
figure(); visualize_number(test_hop_net(w, noisy_digit(five, 0.1), 1))
figure(); visualize_number(test_hop_net(w, noisy_digit(six, 0.1), 1))
figure(); visualize_number(test_hop_net(w, noisy_digit(seven, 0.1), 1))
figure(); visualize_number(test_hop_net(w, noisy_digit(eight, 0.1), 1))
figure(); visualize_number(test_hop_net(w, noisy_digit(nine, 0.1), 1))